### ISSUE TITLE
Saving startAutoCapture to video file

### ISSUE THREAD

**Issue by emptycrown** [jangxx/node-win-desktop-duplication#2]
This package is awesome. Exactly what I was looking for.

Do you happen to have an example of saving the raw startAutoCapture frames into a video file, I'm guessing using ffmpeg?

**Comment by jangxx** [comment]
This library cannot be used to capture a video stream with more than maybe a few frames a second, since there is just way too much overhead involved and I also didn't optimize it for this application.
Also, because the library can't render a video directly, you would have to store every individual image in a file first (which uses a lot of space) and then stitch them into a video later. That is not how desktop capturing is done, since it incurs a ridiculous overhead. Normally, you feed every frame into an encoder directly, which compresses it in parallel, and then stores it as a video directly. This is not possible in Node however.

If you want to capture the desktop using ffmpeg, you might want to look here: https://trac.ffmpeg.org/wiki/Capture/Desktop

**Comment by emptycrown** [comment]
Got it -- makes sense. We've tried ffmpeg capture desktop already and it has too large of a performance overhead for our use case (e.g. capturing gameplay), so we started looking into the native Windows Desktop Duplication API. We may take a stab at extending your code to support video encoding.

**Comment by jangxx** [comment]
And what if you used something like OBS studio? I'm pretty sure it uses the Desktop Duplication API internally, but it also supports a wide range of encoders and is used by people for gameplay recording everywhere.

**Comment by emptycrown** [comment]
Yeah that's one of the first places we looked, but as I understand it, building on top of OBS studio requires us to be open sourced, which isn't feasible currently.

**Comment by jangxx** [comment]
Okay, then I would recommend you building support for the Desktop Duplication API into ffmpeg, which is also open source and probably way easier than trying to use Node.js for real-time video capturing.

**Comment by emptycrown** [comment]
Very helpful -- thank you!

**Comment by hmngwy** [comment]
@EmptyCrown wondering what you guys ended up using for gameplay capture? I'm looking for options, and I'm leaning towards going the DDA route through ffmpeg, but not sure how to go about capturing the desktop audio into the same output, as the options for it in ffmpeg is quite limited. And so, also wondering if you guys cap'ed audio separately from the video, using a separate process, and just merged the two outputs post capture?
