### ISSUE TITLE
[Suggestion] Add a Typescript declaration file

### ISSUE THREAD

**Issue by felladrin** [jangxx/node-win-desktop-duplication#4]
Thanks for creating this lib! A great addition for Node community!

I'd like to suggest adding a type declaration file to the project.

Currently I'm using this custom declaration, to enable intellisense on IDEs:

_windows-desktop-duplication.d.ts_
```typescript
declare module "windows-desktop-duplication" {
    import { EventEmitter } from 'events';
    interface Frame {
        data: Buffer,
        width: Number,
        height: Number
    };
    class DesktopDuplication extends EventEmitter {
        constructor(screenNum: number);
        static getMonitorCount(): number;
        initialize(): void;
        getFrame(retryCount?: number): Frame;
        getFrameAsync(retryCount?: number): Promise<Frame>;
        startAutoCapture(delay: any, allowSkips?: boolean): void;
        stopAutoCapture(clearBacklog?: boolean): void;
    }
}
```

If it's ok for you, you can use it as base. Or if you prefer I can create a pull request for adding it, including additional comments for each function (the same comments you made on Readme, about each method).

**Comment by jangxx** [comment]
I don't personally use TypeScript (yet) and have been using the jshint style comments for some of my other projects, so I'm probably not going to add and test a TypeScript declaration myself, but feel free to open a PR!

 The reason for the absence of even jshint comments is pretty much only, that I haven't yet built any project with this library myself. Usually I'm annoyed by IntelliSense not working while working on my own code, but since I haven't _used_ this library yet, I wasn't yet pushed over the edge to actually properly document everything in code. It would be nice to have of course, so if you feel enticed to document my code, I would happily merge your PR.
